format = """
[](#A6B0FF)\
$os\
$username\
[](bg:#5C41FF fg:#A6B0FF)\
$directory\
[](fg:#5C41FF bg:#44BFFC)\
$git_branch\
$git_status\
[](fg:#44BFFC bg:#70ECBC)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$python\
$rust\
$scala\
[](fg:#70ECBC bg:#81FBA5)\
$docker_context\
[](fg:#81FBA5 bg:#FFFF54)\
$time\
[ ](fg:#FFFF54)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#A6B0FF fg:#0B0B0B"
style_root = "bg:#A6B0FF fg:#0B0B0B"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#A6B0FF"
disabled = true # Disabled by default

[directory]
style = "bg:#5C41FF fg:#FFFFFF"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#70ECBC fg:#0B0B0B"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#81FBA5 fg:#0B0B0B"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#70ECBC fg:#0B0B0B"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#70ECBC fg:#0B0B0B"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#44BFFC fg:#0B0B0B"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#44BFFC fg:#0B0B0B"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#70ECBC fg:#0B0B0B"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#70ECBC fg:#0B0B0B"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#70ECBC fg:#0B0B0B"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#70ECBC fg:#0B0B0B"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#70ECBC fg:#0B0B0B"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#70ECBC fg:#0B0B0B"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#70ECBC fg:#0B0B0B"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#70ECBC fg:#0B0B0B"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#70ECBC fg:#0B0B0B"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#FFFF54 fg:#0B0B0B"
format = '[ ♥ $time ]($style)'


[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "
style = "bg:#70ECBC fg:#0B0B0B"
format = '[ $symbol ($version\[$virtualenv\]) ]($style)'

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "
